# === POSTGRESQL FOR 1GB RAM ===
max_connections = 20
shared_buffers = 128MB
work_mem = 2MB
maintenance_work_mem = 32MB
effective_cache_size = 384MB
wal_buffers = 4MB
checkpoint_completion_target = 0.9
checkpoint_timeout = 10min

# Логи медленных запросов (>500мс)
logging_collector = on
log_directory = '/var/lib/postgresql/data/log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_min_duration_statement = 500
log_line_prefix = '%t [%p]: user=%u,db=%d '